config/routes.rb
Rails.application.routes.draw do
  get 'things/index'

  root 'welcome#index'

  get 'api/schools' => 'schools#api_index'
  get 'api/schools/:id' => 'schools#api_show'
  post 'api/schools' => 'schools#create'

  get 'api/students' => 'students#api_index'
  get 'api/students/:id' => 'students#api_show'
  post 'api/students' => 'students#create'
  patch 'api/students/:id' => 'students#api_update'

  resources :students
  resources :schools
  

end

app/models/match.rb
class Match < ActiveRecord::Base
	belongs_to :school
	belongs_to :student
	
	def self.find_matched_schools student
		matches = student.matches
		schools = []
		matches.each do |match|
			schools.push(School.find(match.school_id))
		end
		return schools
	end

	def self.find_matched_students school
		matches = school.matches
		students = []
		matches.each do |match|
			students.push(Student.find(match.student_id))
		end
		return students
	end

end

app/models/school.rb
class School < ActiveRecord::Base
	has_many :matches
	has_many :students, through: :matches
	belongs_to :student

def self.search(search)
		if search
			# case insensitive
			where('name ILIKE ?', "%#{search}%")
		else
			all
		end
	end

end

app/models/student.rb
class Student < ActiveRecord::Base
	has_many :matches
	has_many :schools, through: :matches
	belongs_to :school

	def self.search(search)
		if search
			# case insensitive
			where('first_name ILIKE ?', "%#{search}%")
		else
			all
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  protect_from_forgery

  after_filter :set_csrf_cookie_for_ng
  
  def set_csrf_cookie_for_ng
  	cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end

  protected
  	def verified_request?
  		super || form_authenticity_token == request.headers['X-XSRF-TOKEN']
  	end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  helper_method :sort_column, :sort_direction

def api_index
  @schools = School.order("id ASC")
end

def api_show
   @school = School.find(params[:id])
   #what does this argument do?
   @students = Match.find_matched_students(@school)
end

def index
	@schools = School.search(params[:search]).order(sort_column + " " + sort_direction)
end

def show
   @school = School.find(params[:id])
   #what does this argument do?
   @students = Match.find_matched_students(@school)
end

def new
	@school = School.new
end

def create
	@school = School.new(school_params)

	if @school.save
     redirect_to @school
   else
    render 'new'

  end

end

# 		sign_in @school
# 		redirect_to @school
# 	else
# 		render :new
# 	end
# end
def edit
  @school = School.find(params[:id])
end 

def update
  @school = School.find(params[:id])
    if @school.update_attributes(school_params)
      redirect_to @school
    else
      render 'edit'
    end
  end

  #  respond_to do |format|
  #     if @school.update_attributes(school_params)
  #       format.html { redirect_to @school, notice: 'School was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @school }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @school.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

def destroy 
 @school = School.find(params[:id])
 @school.destroy
redirect_to schools_path
end

  #   respond_to do |format|
  #     format.html { redirect_to @school, notice: 'School was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

private 
def school_params
	params.require(:school).permit(:name, :email, :picture, :location, :tips, :tuition, :password)
end 

def sort_column
  School.column_names.include?(params[:sort]) ? params[:sort] : "name"
end

def sort_direction
  %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
end


# def find_school
# 	@school = School.find(params[:id])
# end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	helper_method :sort_column, :sort_direction
	
	### API CONTROLLERS ###
	def api_index
	  @students = Student.order("id ASC")
	end

	def api_show
		@student = Student.find(params[:id])
		@schools = Match.find_matched_schools(@student)
	end

	def api_update
		@student = Student.find(params[:id])
		if @student.update_attributes(student_params)
		end
	end
	### API CONTROLLERS ###

	def index
		@students = Student.search(params[:search]).order(sort_column + " " + sort_direction)
	end

	def show
		@student = Student.find(params[:id])
		@schools = Match.find_matched_schools(@student)
	end

	def new
		@student = Student.new
	end

	def create
		@student = Student.new(student_params)
		
		if @student.save
			redirect_to @student
		else
			render 'new'
		end
	end

	def edit
		@student = Student.find(params[:id])
	end

	def update
		@student = Student.find(params[:id])
		if @student.update_attributes(student_params)
			redirect_to @student
		else
			render 'edit'
		end
	end

	def destroy
		@student = Student.find(params[:id])
		if @student.destroy
			# Also delete all match instances associated with student.
			redirect_to students_path
		else 
			render 'show'
		end 
	end

	private

		def student_params
			params.require(:student).permit(:first_name, :last_name, :email, :password)
		end

		def sort_column
			Student.column_names.include?(params[:sort]) ? params[:sort] : "first_name"
		end

		def sort_direction
			%w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
		end
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index

	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def sortable(column, title = nil)
        title ||= column.titleize
        css_class = column == sort_column ? "current #{sort_direction}" : nil
        direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
        link_to "#{title} <i class='#{direction == "desc" ? "glyphicon glyphicon-circle-arrow-down" : "glyphicon glyphicon-circle-arrow-up"}'></i>".html_safe, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
	end

end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IUC Admin</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/schools/_form.html.erb
<%= form_for @school do |f| %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
   <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
   <div class="field">
    <%= f.label :tips %><br>
    <%= f.text_field :tips %>
  </div>
   <div class="field">
    <%= f.label :tuition %><br>
    <%= f.text_field :tuition %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing School</h1>

<%= render 'form' %>

app/views/schools/index.html.erb
<h1>Listing Schools</h1>

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <%= form_tag schools_path, :method => 'get' do %>
  <%= hidden_field_tag :direction, params[:direction] %>
  <%= hidden_field_tag :sort, params[:sort] %>
    <p class="search">
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>
  <br/>
</div>

<div class="table-responsive col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <table class="table table-hover" width="100%">
    <thead>
      <tr>
        <th><%= sortable "name" %></th>
        <th><%= sortable "email" %></th>
        <th><%= sortable "password" %></th> 
        <th><%= sortable "picture" %></th>
        <th><%= sortable "location" %></th>
        <th><%= sortable "tips" %></th>
        <th><%= sortable "tuition" %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @schools.each do |school| %>
        <tr>
          <td><%= school.name %></td>
          <td><%= school.email %></td>
          <td><%= school.password %></td>
          <td><%= school.picture %></td>
          <td><%= school.location %></td>
          <td><%= school.tips %></td>
          <td><%= school.tuition %></td>
          <td><%= link_to 'Show', school %></td>
          <td><%= link_to 'Edit', edit_school_path(school) %></td>
          <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<%= link_to 'New School', new_school_path, class: "btn btn-default" %>
  

app/views/schools/new.html.erb
<h1>New School</h1>

<%= render 'form' %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @school.email %>
</p>
<p>
  <strong>Password:</strong>
  <%= @school.password %>
</p>
<p>
  <strong>Picture:</strong>
  <%= @school.picture %>
</p>
<p>
  <strong>Location:</strong>
  <%= @school.location %>
</p>
<p>
  <strong>tips:</strong>
  <%= @school.tips %>
</p>
<p>
  <strong>tuition:</strong>
  <%= @school.tuition %>
</p>

<h4> Matches </h4>
<% @students.each do |student| %>
  <div>Student #<%= student.id %></div>
<% end %>
<br/>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>
<%= link_to 'Delete', @school, method: "delete" %>

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
	<div><%= f.label :first_name %>:</div>
	<div><%= f.text_field :first_name %></div>
	<div><%= f.label :last_name %>:</div>
	<div><%= f.text_field :last_name %></div>
	<div><%= f.label :email %>:</div>
	<div><%= f.text_field :email %></div>
	<div><%= f.label :password %>:</div>
	<div><%= f.text_field :password %></div>
	<br/>
	<div><%= f.submit %></div>
<% end %>

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/index.html.erb
<h1> Registered Students </h1>

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<%= form_tag students_path, :method => 'get' do %>
	<%= hidden_field_tag :direction, params[:direction] %>
	<%= hidden_field_tag :sort, params[:sort] %>
		<p class="search">
			<%= text_field_tag :search, params[:search] %>
			<%= submit_tag "Search", :name => nil %>
		</p>
	<% end %>
	<br/>
</div>

<div class="table-responsive col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<table class="table table-hover" width="100%"> 
		<thead>
			<tr>
				<th><%= sortable "first_name" %></th>
				<th><%= sortable "last_name" %></th>
				<th><%= sortable "email" %></th>
				<th><%= sortable "password" %></th>
				<th colspan="4"></th>
			</tr>
		</thead>

		<tbody>
			<% @students.each do |student| %>
				<tr>
					<td><%= student.first_name %></td>
					<td><%= student.last_name %></td>
					<td><%= student.email %></td>
					<td><%= student.password %></td>
					<td><%= link_to 'Show', student %></td>
					<td><%= link_to 'Edit', edit_student_path(student) %></td>
					<td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

<br>

<%= link_to "Register New Student", new_student_path, class: "btn btn-default" %>

app/views/students/new.html.erb
<%= render 'form' %>

app/views/students/show.html.erb
<div>First Name: <%= @student.first_name %></div>
<div>Last Name: <%= @student.last_name %></div>
<div>Email: <%= @student.email %></div>
<div>Password: <%= @student.password %></div>
<br/>

<h4> Matches </h4>
<% @schools.each do |school| %>
	<div>School #<%= school.id %></div>
<% end %>
<br/>


<p><%= link_to "Edit", edit_student_path %></p>
<p><%= link_to "Index", students_path %></p>
<p><%= link_to "Delete", @student, method: "delete" %></p>

app/views/things/index.html.erb
<h1>Things#index</h1>
<p>Find me in app/views/things/index.html.erb</p>

app/views/welcome/index.html.erb
Hello